In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [67]:
df=pd.read_csv("/Churn_Modelling.csv")

In [68]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [69]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [70]:
df.duplicated().sum()

0

In [71]:
print(df.columns.tolist())

['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']

In [72]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [73]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [74]:
df=pd.get_dummies(df,columns=['Geography', 'Gender'],drop_first=True)

In [75]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [76]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [77]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [78]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [79]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [80]:
seq=Sequential()

In [81]:
seq.add(Dense(units=11,activation='relu'))
seq.add(Dense(units=10,activation='relu'))
seq.add(Dense(units=1,activation='sigmoid'))

In [83]:
seq.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [93]:
seq.fit(x_train,y_train,batch_size=50,epochs=50,verbose=2,validation_split=0.2)

Epoch 1/50
128/128 - 2s - 15ms/step - accuracy: 0.6984 - loss: 26.5842 - val_accuracy: 0.4613 - val_loss: 35.0821
Epoch 2/50
128/128 - 2s - 17ms/step - accuracy: 0.6923 - loss: 25.8702 - val_accuracy: 0.7900 - val_loss: 16.6501
Epoch 3/50
128/128 - 2s - 14ms/step - accuracy: 0.6933 - loss: 23.3371 - val_accuracy: 0.7919 - val_loss: 8.8509
Epoch 4/50
128/128 - 1s - 5ms/step - accuracy: 0.6988 - loss: 20.9195 - val_accuracy: 0.4731 - val_loss: 31.9823
Epoch 5/50
128/128 - 1s - 10ms/step - accuracy: 0.6947 - loss: 23.3082 - val_accuracy: 0.7944 - val_loss: 14.4177
Epoch 6/50
128/128 - 1s - 4ms/step - accuracy: 0.6841 - loss: 26.2231 - val_accuracy: 0.7987 - val_loss: 61.4581
Epoch 7/50
128/128 - 1s - 5ms/step - accuracy: 0.6977 - loss: 29.6582 - val_accuracy: 0.7937 - val_loss: 37.4772
Epoch 8/50
128/128 - 0s - 3ms/step - accuracy: 0.7052 - loss: 17.4485 - val_accuracy: 0.3756 - val_loss: 22.3830
Epoch 9/50
128/128 - 1s - 5ms/step - accuracy: 0.6870 - loss: 20.1814 - val_accuracy: 0.7987 - val_loss: 35.0537
Epoch 10/50
128/128 - 0s - 3ms/step - accuracy: 0.6931 - loss: 24.4783 - val_accuracy: 0.7856 - val_loss: 10.6756
Epoch 11/50
128/128 - 1s - 4ms/step - accuracy: 0.6938 - loss: 20.1309 - val_accuracy: 0.7987 - val_loss: 71.6974
Epoch 12/50
128/128 - 1s - 5ms/step - accuracy: 0.6827 - loss: 26.5908 - val_accuracy: 0.7987 - val_loss: 90.2280
Epoch 13/50
128/128 - 0s - 3ms/step - accuracy: 0.6906 - loss: 37.6080 - val_accuracy: 0.7987 - val_loss: 72.4386
Epoch 14/50
128/128 - 1s - 5ms/step - accuracy: 0.6906 - loss: 34.9620 - val_accuracy: 0.7131 - val_loss: 4.5619
Epoch 15/50
128/128 - 1s - 5ms/step - accuracy: 0.6944 - loss: 19.3973 - val_accuracy: 0.7944 - val_loss: 10.2968
Epoch 16/50
128/128 - 1s - 6ms/step - accuracy: 0.6913 - loss: 27.6930 - val_accuracy: 0.7987 - val_loss: 30.3044
Epoch 17/50
128/128 - 1s - 6ms/step - accuracy: 0.6964 - loss: 16.2227 - val_accuracy: 0.5781 - val_loss: 6.9798
Epoch 18/50
128/128 - 1s - 5ms/step - accuracy: 0.6914 - loss: 24.9842 - val_accuracy: 0.2994 - val_loss: 36.1421
Epoch 19/50
128/128 - 1s - 5ms/step - accuracy: 0.6769 - loss: 32.2674 - val_accuracy: 0.7981 - val_loss: 31.8951
Epoch 20/50
128/128 - 1s - 10ms/step - accuracy: 0.6888 - loss: 29.8754 - val_accuracy: 0.7163 - val_loss: 7.7085
Epoch 21/50
128/128 - 1s - 7ms/step - accuracy: 0.7072 - loss: 15.8416 - val_accuracy: 0.7294 - val_loss: 7.8744
Epoch 22/50
128/128 - 1s - 5ms/step - accuracy: 0.7025 - loss: 17.6378 - val_accuracy: 0.2812 - val_loss: 25.9352
Epoch 23/50
128/128 - 0s - 3ms/step - accuracy: 0.6909 - loss: 24.5488 - val_accuracy: 0.7931 - val_loss: 18.8743
Epoch 24/50
128/128 - 1s - 4ms/step - accuracy: 0.6911 - loss: 27.3136 - val_accuracy: 0.7962 - val_loss: 11.5669
Epoch 25/50
128/128 - 0s - 3ms/step - accuracy: 0.7039 - loss: 22.1893 - val_accuracy: 0.6225 - val_loss: 9.8942
Epoch 26/50
128/128 - 1s - 5ms/step - accuracy: 0.6914 - loss: 16.8700 - val_accuracy: 0.7969 - val_loss: 48.8133
Epoch 27/50
128/128 - 1s - 6ms/step - accuracy: 0.6966 - loss: 19.5200 - val_accuracy: 0.7950 - val_loss: 20.6632
Epoch 28/50
128/128 - 1s - 4ms/step - accuracy: 0.6842 - loss: 27.5962 - val_accuracy: 0.7944 - val_loss: 17.0427
Epoch 29/50
128/128 - 0s - 3ms/step - accuracy: 0.6917 - loss: 21.6265 - val_accuracy: 0.2325 - val_loss: 67.3932
Epoch 30/50
128/128 - 1s - 5ms/step - accuracy: 0.6961 - loss: 17.4452 - val_accuracy: 0.7950 - val_loss: 21.2257
Epoch 31/50
128/128 - 0s - 3ms/step - accuracy: 0.7013 - loss: 16.6073 - val_accuracy: 0.7950 - val_loss: 36.4003
Epoch 32/50
128/128 - 1s - 5ms/step - accuracy: 0.6914 - loss: 34.6365 - val_accuracy: 0.7887 - val_loss: 11.4548
Epoch 33/50
128/128 - 0s - 3ms/step - accuracy: 0.6825 - loss: 27.0657 - val_accuracy: 0.7937 - val_loss: 12.4248
Epoch 34/50
128/128 - 1s - 6ms/step - accuracy: 0.6903 - loss: 29.8420 - val_accuracy: 0.6938 - val_loss: 10.2556
Epoch 35/50
128/128 - 1s - 4ms/step - accuracy: 0.7013 - loss: 25.6447 - val_accuracy: 0.7937 - val_loss: 28.1160
Epoch 36/50
128/128 - 1s - 5ms/step - accuracy: 0.6978 - loss: 19.0276 - val_accuracy: 0.6075 - val_loss: 7.9754
Epoch 37/50
128/128 - 1s - 5ms/step - accuracy: 0.7111 - loss: 16.2647 - val_accuracy: 0.7937 - val_loss: 18.2126
Epoch 38/50
128/128 - 1s - 7ms/step - accuracy: 0.6808 - loss: 34.9845 - val_accuracy: 0.7862 - val_loss: 9.7133
Epoch 39/50
128/128 - 1s - 9ms/step - accuracy: 0.7023 - loss: 20.6186 - val_accuracy: 0.7950 - val_loss: 37.9700
Epoch 40/50
128/128 - 1s - 5ms/step - accuracy: 0.7017 - loss: 18.3207 - val_accuracy: 0.4494 - val_loss: 9.6945
Epoch 41/50
128/128 - 1s - 5ms/step - accuracy: 0.7005 - loss: 18.6611 - val_accuracy: 0.5587 - val_loss: 6.2253
Epoch 42/50
128/128 - 1s - 8ms/step - accuracy: 0.6988 - loss: 21.8404 - val_accuracy: 0.7900 - val_loss: 10.9212
Epoch 43/50
128/128 - 1s - 5ms/step - accuracy: 0.6923 - loss: 23.8750 - val_accuracy: 0.7944 - val_loss: 22.1980
Epoch 44/50
128/128 - 1s - 5ms/step - accuracy: 0.6855 - loss: 26.6213 - val_accuracy: 0.6662 - val_loss: 9.0155
Epoch 45/50
128/128 - 1s - 5ms/step - accuracy: 0.6869 - loss: 26.7498 - val_accuracy: 0.7894 - val_loss: 10.0461
Epoch 46/50
128/128 - 1s - 5ms/step - accuracy: 0.7020 - loss: 17.3208 - val_accuracy: 0.7944 - val_loss: 25.0377
Epoch 47/50
128/128 - 1s - 5ms/step - accuracy: 0.6936 - loss: 24.0102 - val_accuracy: 0.6675 - val_loss: 13.3209
Epoch 48/50
128/128 - 1s - 5ms/step - accuracy: 0.6958 - loss: 16.8569 - val_accuracy: 0.4044 - val_loss: 25.6814
Epoch 49/50
128/128 - 1s - 5ms/step - accuracy: 0.6858 - loss: 23.5755 - val_accuracy: 0.7831 - val_loss: 10.8888
Epoch 50/50
128/128 - 1s - 5ms/step - accuracy: 0.6891 - loss: 21.0001 - val_accuracy: 0.7956 - val_loss: 42.8757

In [94]:
y_pred = seq.predict(x_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [95]:
y_pred

array([[0.9964261 ],
       [0.10680567],
       [0.6499588 ],
       ...,
       [0.9603631 ],
       [0.31675056],
       [0.51586777]], dtype=float32)

In [96]:
y_pred_binary = (y_pred >= 0.5).astype(int)

In [97]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_binary)

0.6695

In [98]:
seq.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                      │ (50, 11)                    │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (50, 10)                    │             120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (50, 1)                     │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 791 (3.09 KB)

 Trainable params: 263 (1.03 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 528 (2.07 KB)